### ISSUE TITLE
Can't install packages under Windows 11 

### ISSUE THREAD

**Issue by horsto** [bonsai-rx/bonsai#1089]
I am running into this error (see screenshot) when trying to install (many but not all) extensions under Windows 11. I do not run into this problem under Windows 10. I tried resetting permissions recursively of the Bonsai / Packages folder(s), even tried deleting the whole folder and reinstalling. Any ideas? 
<img width="248" alt="Screenshot 2022-10-17 171942" src="https://user-images.githubusercontent.com/7548928/196286398-fdb9e651-5aae-46e8-9fa1-bee1d53abac1.png">

**Comment by glopesdev** [comment]
@horsto can I ask if this is an in-place update from the package manager, or did you download the new installer? There was indeed an issue with Bonsai 2.6 where this could happen that is now fixed in 2.7. Unfortunately to fix this you will need to install 2.7 first from either .zip or .exe and then do the updates.

**Comment by horsto** [comment]
Great, updating to 2.7 did the trick indeed! Thanks
