### ISSUE TITLE
Consider replacing newlines with empty space in text visualizer

### ISSUE THREAD

**Issue by glopesdev** [bonsai-rx/bonsai#1670]
The new text visualizer now strips line endings with empty strings so each value fits in a single row of the buffer. An easy way to preserve some extra readability would be to replace the line endings with a single white space.

**Comment by glopesdev** [comment]
Another option would be to replace all hidden control characters with a rendition of the respective control character, e.g. https://en.wikipedia.org/wiki/Unicode_control_characters#Control_pictures

**Comment by PathogenDavid** [comment]
I did a partial implementation of using control picture replacements. While it does work, legibility with the default fonts on Windows 10 is not ideal:

![image](https://github.com/bonsai-rx/bonsai/assets/278957/cf698bfd-2ed2-4e0f-a491-24c498dfd7d3)

Not sure if it maybe looks better on Windows 11. (During dev club I noticed the control pictures did look different on your screen.) If you want to check here's [my WIP branch](https://github.com/PathogenDavid/bonsai/tree/5108a7c307f7db476c058ef6ca3b872df71e80cb) and [my test file](https://github.com/bonsai-rx/bonsai/files/15069199/test.txt).


I did notice that this visualizer uses `RichTextBox`, so in theory we could dim the glyphs which would probably help. That might complicate things for non-winforms UI frontends though and might be overkill.

Assuming it even matters here, it could also put us down a bad path performance-wise. (I didn't dig super far but `RichTextBox` *does* seem to have a completely separate path for handling plain text.)

**Comment by glopesdev** [comment]
@PathogenDavid good point, we've had issues with high-frequency streams before. We now buffer and batch updates automatically so the impact should be less pronounced but would be nice to have a performant code path by default.

I guess another option might be to just replace the control characters by their literal c# escape characters, i.e. tab with `\t`, newline with `\n`, etc.

@bruno-f-cruz any thoughts or feedback on this?

**Comment by glopesdev** [comment]
@bruno-f-cruz  Yup, I am a bit torn on this one too. The first time I remember hitting this was with matrix representations, either from Math.NET or OpenTK where they would actually include new lines in the `ToString` method result. For that one it is definitely nicer to simply flatten the rows with a regular space separator (since each row is bracketed anyway).

The other case which is more problematic is NetMQ messages where strings can be returned with a `\0` character which literally just kills the control, since we are appending strings and even a single `\0` will prevent any other row from being rendered. In that case it's not clear whether we want to replace `\0` with a space, especially if it ends up being a dump of some kind of buffered character array from a serial port or network.

**Comment by PathogenDavid** [comment]
For the sake of posterity: We discussed this again earlier today during dev club and it was decided that the original proposal (replacing newlines with whitespace) is the ideal solution for now and later we will provide an "advanced" visualization via a package or something similar for those who know and care about control characters.

-------------------

We didn't really talk about how we wanted to handle `\0` in this case. In my current implementation (PR coming soon) I opted to replace it (along with all the other unprintable control characters) with "�" the replacement character.

For reference here's what my current implementation looks like with some additional test strings:

![image](https://github.com/bonsai-rx/bonsai/assets/278957/fa0de164-adc0-4926-bbf4-96ac683e0db8)

Since I had it implemented on Friday and for the sake of comparison, here's what the C# escape sequences implementation would've looked like:

![image](https://github.com/bonsai-rx/bonsai/assets/278957/326f25c4-9499-4328-a0c4-369e34f3ba13)

and for further comparison, here's control pictures with the new sample strings:

![image](https://github.com/bonsai-rx/bonsai/assets/278957/7ef7dc27-d4e7-4316-971c-c9c8488b9200)

(The �s in this case are bring printed by Windows since those are unprintable C1 control characters and have no control pictures.)

For future reference, here are the prototypes pictured above: https://github.com/PathogenDavid/bonsai/commit/d9ac1d85d3da1014cf79a7e94258eff5699af573
