### ISSUE TITLE
Replacing a node with a group workflow when it receives a visualizer mapping generates a bogus source node

### ISSUE THREAD

**Issue by PathogenDavid** [bonsai-rx/bonsai#1792]
This is something that came up when Gonçalo and I were discussing https://github.com/bonsai-rx/bonsai/issues/1769

Starting with the following workflow: [ReplaceNodeWithGroupWorkflowIssue.zip](https://github.com/bonsai-rx/bonsai/files/15281125/ReplaceNodeWithGroupWorkflowIssue.zip)

![ReplaceNodeWithGroupWorkflowIssue](https://github.com/bonsai-rx/bonsai/assets/278957/e013029a-5eca-4286-9618-fa91c63d3154)

Select the `Untitled` `PublishSubject` node. Replace it with a `GroupWorkflow` node (IE: using the "Replace" option from the context menu in the Toolbox.)

This results in the following within the main workflow:

![ReplaceNodeWithGroupWorkflowIssue-Replaced](https://github.com/bonsai-rx/bonsai/assets/278957/eaf01a69-0a2d-45ad-9104-0a0b32e80f81)

But within the group workflow you'll see there's a bogus `Source2` (presumably added for the dashed connection for the visualizer mapping.)

![image](https://github.com/bonsai-rx/bonsai/assets/278957/2130a96a-b7df-42bc-8f84-91b60133f974)

This source shouldn't be here (and in fact does nothing) as visualizer mappings conceptually apply to the node itself rather than any of its sources.

**Comment by glopesdev** [comment]
@PathogenDavid related to this, I found out that grouping the `PublishSubject` with `GroupWorkflow` (rather than replacing) also results in possibly unwanted behavior:

<img alt="image" src="https://github.com/user-attachments/assets/38188403-5679-46d2-879d-8c858a94842f" height="150px"/>

Basically the current behavior of grouping is to eliminate all dashed connections (`ExternalizedProperty`, `VisualizerMapping`, etc) to the newly created group. This is probably not ideal and we might want to revisit this in a separate proposal.

**Comment by PathogenDavid** [comment]
@glopesdev Yeah that doesn't seem ideal. I created a separate issue for it here: https://github.com/bonsai-rx/bonsai/issues/1959
