### ISSUE TITLE
Bonsai 2.8.3.4546 still reports itself as 2.8.2 in Help>About Menu

### ISSUE THREAD

**Issue by banchan86** [bonsai-rx/bonsai#1831]

**Comment by PathogenDavid** [comment]
This is happening because the about box specifically shows the version of `Bonsai.Editor`, but `Bonsai.Editor` didn't have any changes for 2.8.3 so we didn't release a new version of it.

We should probably either show the bootstrapper version there instead or always release a new version of `Bonsai.Editor` regardless.

It might also be a good idea to have the bootstrapper require a specific version of `Bonsai.Editor`, I feel like the minimum version match between the two only has the potential to cause problems. (Might be a good idea for all of the fundamental core Bonsai packages in general.)

**Comment by banchan86** [comment]
Ah I see! Yea it might probably be better to update `Bonsai.Editor` as well so users aren't confused as to whether they had the latest version installed (as I did) haha.

**Comment by PathogenDavid** [comment]
This will be fixed in 2.8.4, thanks for the report!
