### ISSUE TITLE
GetDirectory not inheriting values for Path or SearchPattern parameters

### ISSUE THREAD

**Issue by AOONIH** [bonsai-rx/bonsai#698]
![image](https://user-images.githubusercontent.com/40366898/89053899-ce957580-d34f-11ea-9d8e-254e987a7de0.png)

**Comment by glopesdev** [comment]
@AOONIH We will need a bit more context than this, can you please add a description of what the issue is and how to reproduce it? Is this a runtime issue, or an editor/compiler issue?

I would suggest [asking this question in the user forum](https://groups.google.com/forum/#!forum/bonsai-users) first, so we can help you identify the problem in more detail first. We can then raise the issue in the repository if necessary.

**Comment by glopesdev** [comment]
@AOONIH from looking at the workflow, especially the start of `GetFileStrings`, I am fairly certain this is an issue of property mappings failing to be assigned in time due to branching, [as discussed in this forum question](https://groups.google.com/g/bonsai-users/c/lEj2W_5qgfQ/m/M_hXa_OkAAAJ).

This is a fairly common pitfall to hit, but this slightly counter-intuitive behavior is necessary to ensure all branches receive the exact same data. In the future we are considering solutions to specify different types of anonymous branching, but this is out of the scope of this issue.

The current workaround is to avoid using branching to for externalized property mapping as much as possible, and instead send the values to subjects (e.g. `AsyncSubject`, `ReplaySubject`) which can then be subscribed without branching for the property assignment. This way, the replay or async subject will ensure that all values get replayed to all branches and that values are ready to dispatch as soon as branches are initializing (since by construction subjects are given a chance to initialize first).
