### ISSUE TITLE
Open TK Error message after updating packages

### ISSUE THREAD

**Issue by sarahapark** [bonsai-rx/bonsai#752]
Hello,
I updated the packages and now I'm unable to view the video. Instead, I get an OpenTK error message instead and the Bonsai code will not run. Could you please help?

Error message: MainForm: Could not load file or assembly  'OpenTK, Version=3.1.0.0. Culture = neutral, PublicKeyToken=bad199fe84eb3df4' or one of its dependencies. The system cannot find the file specified.

Thank you!
Sarah

**Comment by glopesdev** [comment]
Hi Sarah,

Please use the support forum first for deployment and configuration questions, we will raise a github issue if/when we manage to identify exactly what the conditions to reproduce this successfully are.

Otherwise, if in the future you feel the need to open an issue directly, please include ALL the following details:
  * operating system
  * the `Bonsai.config` file
  * a detailed list of steps that can be used to reliably reproduce the problem, _starting from scratch_, i.e. uninstall completely Bonsai from your system, reinstall it and take note of the steps; better yet, use the self-contained zip file and this will make it much easier for us to understand what is wrong.
