### ISSUE TITLE
Consider adding DisplayName to AnalogOutput / DigitalOutput

### ISSUE THREAD

**Issue by edmundchong** [bonsai-rx/bonsai#767]
Applying GroupWorkflow and then adding the name also works, but this may be a cleaner solution. Reason for naming these nodes is especially when one is connecting to multiple outputs e.g. with an Arduino and it is difficult to remember which port number corresponds to what :)

**Comment by bruno-f-cruz** [comment]
Hi @edmundchong,

Most of the nodes that interface with specific hardware (e.g. Arduino) have a "create" node. This allows you to have a single node that specifies COM-Arduino Name. 
Moreover, if you want to define the Arduino pin once, and give it a name, a good approach is to use the subjects. Right click "digitalOutput" node (define the pin and arduino you want to use) -> Create Source -> behaviorSubject. This will create a subject with the correct "type" for node (i.e. Bool). To change the state of this pin, simply use a "multicast" to this subject from any place in your code. Since you can give names to these subjects, it makes it very easy to keep track of what is what.
An example can be found here (exercise 1 and 2)
https://neurogears.org/vrp-2021/worksheets/state-machines/
Cheers,
Bruno

**Comment by glopesdev** [comment]
@edmundchong the solution which @bruno-f-cruz recommended is the correct one and makes your workflow not only independent of COM port names but also pin numbers (e.g. if you need to change physical pins for some reason). I will close the issue now.
