### ISSUE TITLE
Some connections between nodes should be allowed when other inputs are disabled

### ISSUE THREAD

**Issue by bruno-f-cruz** [bonsai-rx/bonsai#829]
Consider the example:
![image](https://user-images.githubusercontent.com/7049351/135216250-147dce06-4f37-457f-aadb-021c4e9173c7.png)

Despite missing an input on the **Accumulate** node, connections (using the drag and drop method) are not allowed to be made from the new **Int**.

However, one can go around this by adding a >2 input node and proceed to delete it. E.g.:
![image](https://user-images.githubusercontent.com/7049351/135216547-92caa098-5470-4b37-aeff-913b235e452a.png)
![image](https://user-images.githubusercontent.com/7049351/135216588-cad60a7c-016d-46a6-ab31-7368d7a35a45.png)

Since it looks like there is an implicit behavior for this specific situation (i.e. input validity is checked ignoring disabled nodes),  I think it would be nice to allow users to connect enabled nodes to other nodes without counting disabled nodes to the total input cap. This behavior should also be allowed when connecting disabled nodes to nodes with a caped input. 

Thanks :)

B

**Comment by RoboDoig** [comment]
There are some edge cases to consider here, e.g. 'overload' like functionality in GroupedWorkflows.

Ultimately, the compiler is the only process that knows for sure what a node's inputs (and types etc.) will be. Just using the editor workflow to evaluate valid inputs is not sufficient in some cases.

**Comment by glopesdev** [comment]
@RoboDoig that is absolutely correct. However, there is also a bit of a chicken and egg problem here in situations where the build fails for some reason (i.e. a builder node throws an exception). Because the current version of the compiler does not support partial compilation, in such a case we would actually be unable to determine how many inputs are connected to the node.

This would be particularly problematic and ironic if to fix the build error we would need to make a connection between two nodes that we are prevented of connecting because the build has failed.

For now to avoid this issue and still make progress on this issue I suggest we proceed on the basis of a simple syntactic check, basically by traversing all connections from sources to the target node to determine if there are any branches consisting entirely of disabled nodes which can be safely eliminated from the connection count.
