### ISSUE TITLE
Consider adding UI shortcuts to close group tabs

### ISSUE THREAD

**Issue by bruno-f-cruz** [bonsai-rx/bonsai#963]
The only way to close group tabs, at the moment, is to interact with the small `x` icon. To improve user experience, one might consider mimicking common browser shortcuts. Using the middle mouse button and the keyboard shortcut `Control+W` might be good options.

**Comment by glopesdev** [comment]
There is already a shortcut for closing tabs (`Ctrl+F4`) and a shortcut for closing nested editor windows (`Alt+F4`).

I didn't know that `Ctrl+W` was the standard for closing tabs in browsers, but apparently `Ctrl+F4` also does it in Windows. The reason I like using the Function keys is that they are less likely to interfere with normal keyboard operation, but it's not a very strong argument, so I'm happy to consider changing it for next release.

I also wonder if closing the main Workflow tab with `Ctrl+F4` should try to close the nested editor window. Currently this is not allowed, so you have to close the main window with `Alt+F4`, but I notice that on browsers as soon as the last tab is closed the window is closed as well. I guess currently in the editor the tabs are not really independent, which is why I was more fearful of accidental closures.
